### ISSUE TITLE
Hero Page

### ISSUE THREAD

**Issue by gerwinf** [WunderPass/docker-compose-wunderpool-landingpagev2#1]
1) Das Wunder im WunderPool Logo ist nicht scharf. Bitte nochmal mit höherer Auflösung hochladen

2) Header Text könnte rechts mehr marge haben und mehr komprimiert sein bei großer Auflösung, damit es immer zweizeilig ist, somit tiefer und mit weniger Whitespace

3) Buttons sollten näher aneinander wie bei Figma

4) Font im Header Text sollte in Graphik sein wie bei Figma

![Screenshot 2022-03-10 at 11 53 20](https://user-images.githubusercontent.com/6452126/157647692-22b2aea5-2309-4445-968f-7d26784113cf.png)

![Screenshot 2022-03-10 at 12 31 57](https://user-images.githubusercontent.com/6452126/157653554-650a6f15-43e1-4d25-b0e1-e95590818e69.png)

**Comment by AlpCentaur** [comment]
1. wunder im Logo nicht scharf ist gefixt
