### ISSUE TITLE
Übergang auf Mobile

### ISSUE THREAD

**Issue by gerwinf** [WunderPass/docker-compose-wunderpool-landingpagev2#3]
Hier dürfen die Images nicht aneinander geraten. Da muss noch mehr von dem jeweiligen Hintergründen dazu kommen. 

![Screenshot 2022-03-10 at 12 52 52](https://user-images.githubusercontent.com/6452126/157656581-0b8ea386-5fd7-4935-a8d9-eba6dab45037.png)

**Comment by AlpCentaur** [comment]
Habe ich bereits gelöst wie es für mich aussieht..
Schau mal am besten im aktuellen commit, mir erscheint der Fehler nicht : )
