### ISSUE TITLE
WunderPass NFT is missing.

### ISSUE THREAD

**Issue by DespotB** [WunderPass/docker-compose-wunderpool-landingpagev2#8]
This section is missing completely. (was this later changed?
If wanted like this close this issue else add it.

![image](https://user-images.githubusercontent.com/43843062/163987804-3c159ffa-bb55-4faa-bd17-d3f49e6f5add.png)

**Comment by AlpCentaur** [comment]
The idea was, that the WunderNFT is one topic to far away from the pools. In this sense it was intentionally changed, and it is not about something missing
